// File generated by FlutterFire CLI (deduplicated).
// ignore_for_file: public_member_api_docs, sort_constructors_first

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi-FPn6ynMFMyXEBGYHS0eX0neBhq76LQ',
    authDomain: null,
    projectId: 'property-fee-app-db',
    storageBucket: 'property-fee-app-db.firebasestorage.app',
    messagingSenderId: '711087650599',
    appId: '1:711087650599:web:0000000000000000000000',
    measurementId: null,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-FPn6ynMFMyXEBGYHS0eX0neBhq76LQ',
    appId: '1:711087650599:android:eacd1980b9e9120fce5b02',
    messagingSenderId: '711087650599',
    projectId: 'property-fee-app-db',
    storageBucket: 'property-fee-app-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA76fhJDiRXcMjZJseKPV7wNCpR8WyUE1E',
    appId: '1:711087650599:ios:eccfb6713519c5bfce5b02',
    messagingSenderId: '711087650599',
    projectId: 'property-fee-app-db',
    storageBucket: 'property-fee-app-db.firebasestorage.app',
    iosClientId:
        '711087650599-9tnunumtr1ip4fn5ia6v84j4u4enicb5.apps.googleusercontent.com',
    iosBundleId: 'com.xmum.propertyfee.propertyFeeApp',
  );
}